name: Destroy ECS Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      confirm_destroy:
        description: 'Type "DESTROY" to confirm destruction'
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.5.0

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Validate confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY" ]; then
          echo "Confirmation failed. You must type 'DESTROY' to proceed."
          exit 1
        fi
        echo "Confirmation validated. Proceeding with destruction..."

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      working-directory: ./infrastructure
      run: terraform init

    - name: Terraform Plan Destroy
      working-directory: ./infrastructure
      run: |
        terraform plan -destroy \
          -var="project_name=CT-ECS-${{ github.event.inputs.environment }}" \
          -var="common_tags={Environment=\"${{ github.event.inputs.environment }}\",Project=\"nodejs-app\",ManagedBy=\"terraform\"}" \
          -out=destroy-plan

    - name: Terraform Destroy
      working-directory: ./infrastructure
      run: terraform apply -auto-approve destroy-plan

    - name: Cleanup Summary
      run: |
        echo "## Infrastructure Destruction Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "All resources have been successfully destroyed." >> $GITHUB_STEP_SUMMARY